# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdf_multinomial_lnP <- function(K, N, p, n) {
    .Call('_pmultinom_cdf_multinomial_lnP', PACKAGE = 'pmultinom', K, N, p, n)
}

